parameters:
    # orm managers
    orm.manager.schema: JohnKrovitch\ORMBundle\Manager\SchemaManager
    orm.manager.source: JohnKrovitch\ORMBundle\Manager\SourceManager
    orm.manager.driver: JohnKrovitch\ORMBundle\Manager\DriverManager

    # orm drivers
    orm.driver.mysql:  JohnKrovitch\ORMBundle\Database\Connection\Driver\MysqlDriver
    orm.driver.yml:    JohnKrovitch\ORMBundle\Database\Connection\Driver\YmlDriver

    # orm translators
    orm.translator.mysql: JohnKrovitch\ORMBundle\Database\Connection\Translator\MysqlTranslator
    orm.translator.yml: JohnKrovitch\ORMBundle\Database\Connection\Translator\YmlTranslator

    # utils
    orm.utils.sanitizer: JohnKrovitch\ORMBundle\Utils\Sanitizer

services:
    # orm managers
    orm.manager.schema:
        class: %orm.manager.schema%
        calls:
            - [setContainer, [@service_container]]
            - [setSourceManager, [@orm.manager.source]]

    orm.manager.source:
        class: %orm.manager.source%

    orm.manager.driver:
        class: %orm.manager.driver%
        calls:
            - [setContainer, [@service_container]]

    # orm drivers
    orm.driver.mysql:
        class: %orm.driver.mysql%
        calls:
            - [setTranslator, [@orm.translator.mysql]]

    orm.driver.yml:
        class: %orm.driver.yml%
        calls:
            - [setTranslator, [@orm.translator.yml]]

    # orm translators
    orm.translator.mysql:
        class: %orm.translator.mysql%
        calls:
            - [setSanitizer, [@orm.utils.sanitizer]]

    orm.translator.yml:
        class: %orm.translator.yml%
        calls:
            - [setSanitizer, [@orm.utils.sanitizer]]

    orm.utils.sanitizer:
        class: %orm.utils.sanitizer%