parameters:
    # database
    orm.database: JohnKrovitch\ORMBundle\Database\Database
    # orm managers
    orm.manager.schema: JohnKrovitch\ORMBundle\Manager\SchemaManager
    orm.manager.source: JohnKrovitch\ORMBundle\Manager\SourceManager
    orm.manager.driver: JohnKrovitch\ORMBundle\Manager\DriverManager

services:
    # database
    orm.database:
        class: %orm.database%


    # managers
    orm.manager.schema:
        class: %orm.manager.schema%
        calls:
            - [setContainer, [@service_container]]
            - [setSourceManager, [@orm.manager.source]]

    orm.manager.source:
        class: %orm.manager.source%

    orm.manager.driver:
        class: %orm.manager.driver%