parameters:
    # orm behaviors
    orm.behavior.unique:        JohnKrovitch\ORMResourceBundle\ORMBehavior\UniqueBehavior
    orm.behavior.timestampable: JohnKrovitch\ORMResourceBundle\ORMBehavior\TimestampableBehavior

    # orm managers
    orm.manager.behavior:       JohnKrovitch\ORMResourceBundle\Manager\BehaviorManager

services:
    # orm behaviors
    orm.behavior.unique:
        class: %orm.behavior.unique%
        tags:
            - {name: orm.behavior, alias: unique}

    orm.behavior.timestamapble:
        class: %orm.behavior.timestampable%
        tags:
            - {name: orm.behavior, alias: timestampable}

    # orm managers
    orm.manager.behavior:
        class: %orm.manager.behavior%